

NetherWorldName: "world_the_end"

PortalStatusTimes:              # times in milliseconds
  Cast: 15000
  Activation: 5000
  Active: 30000             

PortalCastAnimation:
  MaxNumberOfParticles: 12      # number of created particles 
  NumberOfRotations: 2          # number of the rotations around the player in one cast time
  MaxRadius: 3                  # maximal radius of the animation around the player
  ParticleSpeed: 0.01           # speed of particles in the rotation

